# Generated by Django 4.1.7 on 2023-03-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='statusorder',
            new_name='statord',
        ),
        migrations.RenameField(
            model_name='typeof',
            old_name='typepet',
            new_name='typet',
        ),
    ]
